#!/usr/bin/env python3
"""Generates src/crypto/ecdh_vectors.rs: known answers for the constant-time P-256 / P-384 ECDH code.

The expected values come from the Python `cryptography` package (OpenSSL), an implementation
independent of this crate. Two tables:

  PUBLIC  (curve, scalar, uncompressed public key)             the scalar multiple of the generator
  SHARED  (curve, scalar, peer public key, shared secret)      the ECDH x-coordinate

The scalars include the edges (1, 2, 3, n-1, n-2, values with long runs of 0 and 1 bits, small values)
and deterministic pseudo-random ones.

Usage: python3 tools/gen_ecdh_vectors.py > src/crypto/ecdh_vectors.rs
"""
import hashlib

from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization

CURVES = {
    "p256": (ec.SECP256R1(), 32, 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551),
    "p384": (ec.SECP384R1(), 48, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973),
}


def det(curve, idx):
    """Deterministic pseudo-random scalar in [1, n-1]."""
    _, size, n = CURVES[curve]
    d = hashlib.sha512(f"tiny_https ecdh {curve} {idx}".encode()).digest()
    d += hashlib.sha512(d).digest()
    return int.from_bytes(d[:size], "big") % (n - 1) + 1


def scalars(curve):
    _, size, n = CURVES[curve]
    bits = size * 8
    edge = [1, 2, 3, 4, 5, 15, 16, 17, 255, 256, 0xFFFF, 2**64 - 1, 2**64, 2**127, 2**128 + 1,
            2**(bits - 1), 2**(bits - 1) - 1, n - 1, n - 2, n - 3, (n - 1) // 2, (n + 1) // 2,
            int("10" * (bits // 2), 2) % n, int("01" * (bits // 2), 2) % n,
            (2**(bits - 8) - 1), int("1" * (bits - 1), 2) % n,
            int("0" * 8 + "1" * (bits - 8), 2) % n,
            int("1" * 4 + "0" * (bits - 4), 2) % n]
    edge = [e for e in edge if 1 <= e < n]
    return edge + [det(curve, i) for i in range(12)]


def point(pub):
    return pub.public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)


def key(curve, d):
    return ec.derive_private_key(d, CURVES[curve][0])


def main():
    out = []
    out.append("//! GENERATED by tools/gen_ecdh_vectors.py from Python's `cryptography` package. Do not edit.")
    out.append("//!")
    out.append("//! `PUBLIC`: (curve, scalar, uncompressed public key). `SHARED`: (curve, scalar, peer public key,")
    out.append("//! shared secret = x coordinate of scalar * peer).")
    out.append("")
    pub_rows, shared_rows = [], []
    for curve, (_, size, n) in CURVES.items():
        sc = scalars(curve)
        for d in sc:
            pub_rows.append((curve, d.to_bytes(size, "big").hex(), point(key(curve, d).public_key()).hex()))
        # pairs: every scalar against the next scalar's public key, plus against the edge keys
        for i, d in enumerate(sc):
            for peer in (sc[(i + 1) % len(sc)], sc[(i + 7) % len(sc)]):
                k = key(curve, d)
                peer_pub = key(curve, peer).public_key()
                secret = k.exchange(ec.ECDH(), peer_pub)
                shared_rows.append((curve, d.to_bytes(size, "big").hex(), point(peer_pub).hex(), secret.hex()))
    out.append("pub static PUBLIC: &[(&str, &str, &str)] = &[")
    for r in pub_rows:
        out.append(f'    ("{r[0]}", "{r[1]}", "{r[2]}"),')
    out.append("];")
    out.append("")
    out.append("pub static SHARED: &[(&str, &str, &str, &str)] = &[")
    for r in shared_rows:
        out.append(f'    ("{r[0]}", "{r[1]}", "{r[2]}", "{r[3]}"),')
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main()
