#!/usr/bin/env python3
"""Generates src/crypto/aead_vectors.rs: test vectors for ChaCha20-Poly1305, Poly1305 and AES-GCM.

The expected values come from the Python `cryptography` package (OpenSSL), i.e. an
implementation independent of this crate. Inputs are deterministic functions of an index so the
Rust tests can rebuild them without storing them (see `det_*` in src/crypto/aead_vectors.rs).

Usage: python3 tools/gen_aead_vectors.py > src/crypto/aead_vectors.rs
"""
import hashlib
import random

from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305
from cryptography.hazmat.primitives.poly1305 import Poly1305


def det_key(idx, n):
    return bytes((idx * 7 + i * 13 + 1) & 255 for i in range(n))


def det_nonce(idx):
    return bytes((idx * 11 + i * 5 + 3) & 255 for i in range(12))


def det_aad(idx, n):
    return bytes((idx * 3 + i * 17 + 5) & 255 for i in range(n))


def det_pt(idx, n):
    return bytes((i * 131 + idx + 7) & 255 for i in range(n))


PT_LENS = [0, 1, 15, 16, 17, 31, 32, 33, 63, 64, 65, 127, 128, 129, 191, 192, 193, 255, 256, 257,
           300, 511, 512, 513, 767, 768, 769, 1000, 1024, 2048, 4096, 5000]
AAD_LENS = [0, 1, 12, 13, 16, 17, 31, 32, 100]


def h(b):
    return b.hex()


def main():
    out = []
    out.append("//! GENERATED by tools/gen_aead_vectors.py from Python's `cryptography` package. Do not edit.")
    out.append("//!")
    out.append("//! Each AEAD row is (index, key_len, plaintext_len, aad_len, sha256(ciphertext), tag). The inputs are")
    out.append("//! rebuilt by the `det_*` functions below (they mirror the generator).")
    out.append("")
    out.append("pub fn det_key(idx: usize, n: usize) -> Vec<u8> {")
    out.append("    (0..n).map(|i| ((idx * 7 + i * 13 + 1) & 255) as u8).collect()")
    out.append("}")
    out.append("pub fn det_nonce(idx: usize) -> [u8; 12] {")
    out.append("    core::array::from_fn(|i| ((idx * 11 + i * 5 + 3) & 255) as u8)")
    out.append("}")
    out.append("pub fn det_aad(idx: usize, n: usize) -> Vec<u8> {")
    out.append("    (0..n).map(|i| ((idx * 3 + i * 17 + 5) & 255) as u8).collect()")
    out.append("}")
    out.append("pub fn det_pt(idx: usize, n: usize) -> Vec<u8> {")
    out.append("    (0..n).map(|i| ((i * 131 + idx + 7) & 255) as u8).collect()")
    out.append("}")
    out.append("")

    def rows(kind):
        res = []
        for idx, n in enumerate(PT_LENS):
            alen = AAD_LENS[idx % len(AAD_LENS)]
            klen = 32 if kind == "chacha" else (16 if idx % 2 == 0 else 32)
            key, nonce = det_key(idx, klen), det_nonce(idx)
            aad, pt = det_aad(idx, alen), det_pt(idx, n)
            aead = ChaCha20Poly1305(key) if kind == "chacha" else AESGCM(key)
            ct_tag = aead.encrypt(nonce, pt, aad)
            ct, tag = ct_tag[:-16], ct_tag[-16:]
            res.append((idx, klen, n, alen, hashlib.sha256(ct).hexdigest(), tag.hex()))
        return res

    for name, kind in (("CHACHA_VECTORS", "chacha"), ("GCM_VECTORS", "gcm")):
        out.append(f"pub const {name}: &[(usize, usize, usize, usize, &str, &str)] = &[")
        for r in rows(kind):
            out.append(f'    ({r[0]}, {r[1]}, {r[2]}, {r[3]}, "{r[4]}", "{r[5]}"),')
        out.append("];")
        out.append("")

    # Poly1305: (key, message, tag), all hex. Edge cases first, then random.
    polys = []
    rng = random.Random(8439)
    max_r = bytes.fromhex("ffffffffffffffffffffffffffffffff")  # clamped by the implementation
    ff = b"\xff" * 16
    zero = bytes(16)
    keys = [
        max_r + ff,                      # r all ones before clamping, s all ones
        max_r + zero,
        zero + ff,                       # r = 0
        bytes.fromhex("01000000000000000000000000000000") + zero,   # r = 1
        bytes.fromhex("02000000000000000000000000000000") + zero,
        bytes.fromhex("0000000000000000000000000000000000000000000000000000000000000000"),
    ]
    for k in keys:
        for n in (0, 1, 15, 16, 17, 32, 33, 48, 64, 65, 96, 112, 128, 129, 255):
            polys.append((k, b"\xff" * n))
            polys.append((k, bytes(n)))
    # RFC 8439 A.3 #5/#6 style: values near 2^130 - 5
    k5 = bytes.fromhex("02" + "00" * 15) + bytes(16)
    polys.append((k5, bytes.fromhex("ff" * 16)))
    k6 = bytes.fromhex("02" + "00" * 15) + bytes.fromhex("ff" * 16)
    polys.append((k6, bytes.fromhex("02" + "00" * 15)))
    # h reduces to exactly p, p+1, ...: message = 0xfb ff.. ff 03 (little endian 2^130-5 split in blocks)
    polys.append((bytes.fromhex("01" + "00" * 15) + bytes(16),
                  bytes.fromhex("fbffffffffffffffffffffffffffffff" + "03000000000000000000000000000000")[:17]))
    for i in range(60):
        k = bytes(rng.randrange(256) for _ in range(32))
        n = rng.choice([0, 1, 2, 15, 16, 17, 31, 32, 33, 47, 48, 49, 63, 64, 65, 100, 255, 256, 257, 1000])
        polys.append((k, bytes(rng.randrange(256) for _ in range(n))))
    out.append("/// (key, message, tag) as hex.")
    out.append("pub const POLY1305_VECTORS: &[(&str, &str, &str)] = &[")
    for k, m in polys:
        tag = Poly1305.generate_tag(k, m)
        out.append(f'    ("{k.hex()}", "{m.hex()}", "{tag.hex()}"),')
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main()
