#!/usr/bin/env python3
"""Generates tests/data/sumdb_synthetic.txt: a small made-up checksum database, signed with a test
key, in two histories that agree up to a point and then differ (record 17 is another record in the
second), so that src/sumdb.rs can be tested against forks, which a real server never shows.
Run from the repository root: python3 tools/gen_sumdb_synthetic.py

Format, one item per line:
  key <verifier key string>
  head <name> <hex of the signed tree head note>        h200, h300 (honest), f250, f300 (forked)
  lookup <name> <module> <version> <hex of the response>
  tile <history> <path> <hex>                           history H or F: the tiles of the 300-leaf tree

The key derives from a seed written below; the file holds public data only.
"""
import base64
import hashlib
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519
from tlog_vectors import leaf_hash, lpt, node

NAME = "sumdb.test"


def b64(b):
    return base64.b64encode(b).decode()


def record(i, evil=False):
    mod = f"example.com/m{i}"
    h1 = hashlib.sha256(b"%d%s" % (i, b" evil" if evil else b"")).digest()
    h2 = hashlib.sha256(b"%d go.mod" % i).digest()
    return f"{mod} v1.0.0 h1:{b64(h1)}\n{mod} v1.0.0/go.mod h1:{b64(h2)}\n"


def mth(leaves, lo, hi):
    n = hi - lo
    if n == 1:
        return leaves[lo]
    k = lpt(n)
    return node(mth(leaves, lo, lo + k), mth(leaves, lo + k, hi))


seed = hashlib.sha256(b"tiny_https synthetic sumdb key").digest()
sk = ed25519.Ed25519PrivateKey.from_private_bytes(seed)
pub = sk.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
keydata = b"\x01" + pub
khash = hashlib.sha256(NAME.encode() + b"\n" + keydata).digest()[:4]


def head(leaves, n):
    text = f"go.sum database tree\n{n}\n{b64(mth(leaves, 0, n))}\n".encode()
    sig = sk.sign(text)
    return text + b"\n" + f"— {NAME} {b64(khash + sig)}\n".encode()


def response(i, text, note):
    return f"{i}\n{text}\n".encode() + note


H = [leaf_hash(record(i).encode()) for i in range(300)]
F = [leaf_hash(record(i, evil=(i == 17)).encode()) for i in range(300)]
out = [f"# generated by tools/gen_sumdb_synthetic.py; a made-up log under a test key"]
out.append(f"key {NAME}+{khash.hex()}+{b64(keydata)}")
heads = {"h200": head(H, 200), "h300": head(H, 300), "f250": head(F, 250), "f300": head(F, 300)}
for k, v in heads.items():
    out.append(f"head {k} {v.hex()}")
lookups = [
    ("h300_250", 250, record(250), heads["h300"]),
    ("h300_17", 17, record(17), heads["h300"]),
    ("h200_150", 150, record(150), heads["h200"]),
    ("f300_17", 17, record(17, evil=True), heads["f300"]),
    # the forked record under the honest head: the log does not have it there
    ("mix_17", 17, record(17, evil=True), heads["h300"]),
]
for name, i, text, note in lookups:
    out.append(f"lookup {name} example.com/m{i} v1.0.0 {response(i, text, note).hex()}")
for hist, leaves in (("H", H), ("F", F)):
    out.append(f"tile {hist} tile/8/0/000 {b''.join(leaves[:256]).hex()}")
    out.append(f"tile {hist} tile/8/0/001.p/44 {b''.join(leaves[256:300]).hex()}")
    out.append(f"tile {hist} tile/8/1/000.p/1 {mth(leaves, 0, 256).hex()}")
with open("tests/data/sumdb_synthetic.txt", "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote tests/data/sumdb_synthetic.txt")
