#!/usr/bin/env python3
"""Generates tests/data/note_fixtures.txt: signed-note signatures made with three fixed Ed25519 test keys
(Python `cryptography`; the keys derive from seeds written below, so the output is reproducible and
holds public data only). Run from the repository root: python3 tools/gen_note_fixtures.py

File format, one item per line:
  key <label> <verifier key string>
  text <label> <hex of the text, which ends in a newline>
  sig <text label> <key label> <the signature line, without its newline>

The tests in src/note.rs put notes together from these (text, blank line, chosen signature lines) and
damage them.
"""
import base64
import hashlib

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519

KEYS = {
    "alpha": "alpha.example",
    "beta": "beta.example",
    "gamma": "gamma.example",
}
TEXTS = {
    "tree": b"go.sum database tree\n42\n" + base64.b64encode(hashlib.sha256(b"root").digest()) + b"\n",
    "plain": b"hello, world\n",
    "unicode": "héllo — ✓ \U0001F600\n".encode(),
    "lines": b"origin\n7\nAAAA\nextra line\nanother\n",
}

out = ["# generated by tools/gen_note_fixtures.py; test keys, public data only"]
signers = {}
for label, name in KEYS.items():
    seed = hashlib.sha256(b"tiny_https note fixture key " + label.encode()).digest()
    sk = ed25519.Ed25519PrivateKey.from_private_bytes(seed)
    pub = sk.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    keydata = b"\x01" + pub
    khash = hashlib.sha256(name.encode() + b"\n" + keydata).digest()[:4]
    signers[label] = (name, sk, khash)
    out.append(f"key {label} {name}+{khash.hex()}+{base64.b64encode(keydata).decode()}")
for tlabel, text in TEXTS.items():
    out.append(f"text {tlabel} {text.hex()}")
for tlabel, text in TEXTS.items():
    for label, (name, sk, khash) in signers.items():
        sig = sk.sign(text)
        out.append(f"sig {tlabel} {label} — {name} {base64.b64encode(khash + sig).decode()}")
open("tests/data/note_fixtures.txt", "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote tests/data/note_fixtures.txt")
