#!/usr/bin/env python3
"""Generates tests/data/rsa_vectors.txt: RSA signatures that the CMS verifier needs and the older
vectors do not cover, made with Python `cryptography` (OpenSSL underneath): PKCS#1 v1.5 over SHA-1
(legacy signatures, which `cms` reports as weak) and RSASSA-PSS with other salt lengths and a
message hash different from the MGF1 hash (what an RSASSA-PSS-params structure can say; PSS with SHA-1
is left out because the library has no SHA-1 for it, and `cms` reports such a signer as unsupported). A fresh
2048-bit key is made on every run and thrown away: only the public key and the signatures are
written, so rerunning changes the file. Run from the repository root:
python3 tools/gen_rsa_vectors.py

  key <n hex> <e hex>
  pkcs1 <hash> <message hex> <signature hex>
  pss <hash> <mgf hash> <salt length> <message hex> <signature hex>
"""
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

def be(x):
    return x.to_bytes((x.bit_length() + 7) // 8, "big").hex()


H = {"sha1": hashes.SHA1, "sha256": hashes.SHA256, "sha384": hashes.SHA384, "sha512": hashes.SHA512}
key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
pub = key.public_key().public_numbers()
out = ["# generated by tools/gen_rsa_vectors.py; a throwaway key, public data only", f"key {be(pub.n)} {be(pub.e)}"]
msg = b"tiny_https rsa vectors: the message that is signed"
for h in ("sha1", "sha256", "sha384", "sha512"):
    sig = key.sign(msg, padding.PKCS1v15(), H[h]())
    out.append(f"pkcs1 {h} {msg.hex()} {sig.hex()}")
for h, mgf, salt in [("sha256", "sha256", 32), ("sha256", "sha256", 0), ("sha256", "sha256", 20), ("sha256", "sha512", 16), ("sha384", "sha384", 48), ("sha384", "sha256", 48), ("sha512", "sha512", 64),
                     ("sha256", "sha256", 222)]:
    sig = key.sign(msg, padding.PSS(mgf=padding.MGF1(H[mgf]()), salt_length=salt), H[h]())
    out.append(f"pss {h} {mgf} {salt} {msg.hex()} {sig.hex()}")
open("tests/data/rsa_vectors.txt", "w").write("\n".join(out) + "\n")
print("wrote tests/data/rsa_vectors.txt")
